apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pac-pipeline-annotation 
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]" 
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipeline.yaml]"
    pipelinesascode.tekton.dev/task-0: "[.tekton/task.yaml]"
spec: 
  params:
  - name: message
    value: "Hello"
  pipelineRef:
    name: pac-pipeline
